language: objective-c

branches:
 only:
 - master

xcode_project: SkyFloatingLabelTextField/SkyFloatingLabelTextField.xcodeproj
xcode_scheme: SkyFloatingLabelTextField
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

before_install:
    - gem install slather --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build test -project SkyFloatingLabelTextField/SkyFloatingLabelTextField.xcodeproj -scheme SkyFloatingLabelTextField -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2'

after_success:
  - cd $TRAVIS_BUILD_DIR && slather
